[package]
name = "dolbaeb_simulator"
version = "0.1.1"
edition = "2021"

[dependencies]
macroquad = { version = "=0.4.13", features = ["audio"] }
serde = { version = "1.0", features = ["derive"] }
fontdue = "=0.9.2"
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev.package."*"]
opt-level = 3

[package.metadata.android]
package_name = "com.dolbaeb.dolbaeb_simulator"
label = "Dolbaeb Simulator"
build_targets = ["aarch64-linux-android"]
target_sdk_version = 30
