name: Build Android APK

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/root/src \
            -w /root/src \
            notfl3/cargo-apk /bin/bash -c "rm -f Cargo.lock && cargo update -p fontdue --precise 0.9.2 && cargo quad-apk build --release"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolbaeb-simulator-apk
          path: target/android-artifacts/release/apk/*.apk
